#! /usr/bin/env python2

from sys import *

# LATEX templates ==========================================
def latex_template(latex_flags):
    s = \
r"""\documentclass{article}

\usepackage[utf8x]{inputenc}%s
\usepackage{verbatim}%s%s

\title{Titulo}
\author{Joshua Emmanuel Mendoza Mendieta}
\date{\today}

\begin{document}
\maketitle



\end{document}
"""

    margin = r"""
\usepackage[margin=2cm]{geometry}"""
    graphicx = r"""
\usepackage{graphicx}"""
    math = r"""
\usepackage{amsmath, amsfonts, amssymb}"""


    try:
        latex_flags.index("all")
        return s % (margin, graphicx, math)
    except ValueError:
        try:
            latex_flags.index("margin")
        except ValueError:
            margin = ""
        try:
            latex_flags.index("math")   
        except ValueError:
            math = ""
        try:
            latex_flags.index("graphicx")
        except ValueError:
            graphicx = ""

        return s % (margin, graphicx, math)
        
# C templates ==============================================

def c_template(c_flags):
    s = \
r"""#include <stdio.h>
#include <stdlib.h>%s

int main(int argc, char** argv)
{


    return 0;
}
"""

    math = r"""
#include <math.h>"""

    try:
        c_flags.index("math")
    except ValueError:
        math = ""

    return s % math

# mktemplate program ========================================
args = argv[1:]

if len(args) == 0:
    print "Usage: mktemplate {latex {all | {[math] [margin] [graphicx]}}| c [math]}"
    exit(1)

t = args[0] # Main type

if t == "latex":
    print latex_template(args[1:])
elif t == "c":
    print c_template(args[1:])
else:
    print t, "is an unsupported template type"
#============================================================
